# Generated by Django 5.0 on 2025-12-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='room',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Кабинет/Офис'),
        ),
    ]
