# Generated by Django 5.0 on 2026-01-20 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workstation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=100, verbose_name='Кабинет/Офис')),
                ('number', models.CharField(help_text='Например: "ПК-1", "Левый стол", "Монитор 3" и т.д.', max_length=50, verbose_name='Номер/Описание')),
                ('location', models.CharField(blank=True, help_text='Опционально: уточнённое место расположения', max_length=255, verbose_name='Подробное местоположение')),
            ],
            options={
                'verbose_name': 'Рабочее место',
                'verbose_name_plural': 'Рабочие места',
                'ordering': ['room', 'number'],
                'unique_together': {('room', 'number')},
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='workstation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.workstation', verbose_name='Рабочее место/Компьютер'),
        ),
    ]
