# Generated by Django 5.0 on 2026-04-05 11:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_userprofile_workstation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Р’Р»РѕР¶РµРЅРёРµ', 'verbose_name_plural': 'Р’Р»РѕР¶РµРЅРёСЏ'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'РљРѕРјРјРµРЅС‚Р°СЂРёР№', 'verbose_name_plural': 'РљРѕРјРјРµРЅС‚Р°СЂРёРё'},
        ),
        migrations.AlterModelOptions(
            name='priority',
            options={'ordering': ['-name'], 'verbose_name': 'РџСЂРёРѕСЂРёС‚РµС‚', 'verbose_name_plural': 'РџСЂРёРѕСЂРёС‚РµС‚С‹'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['name'], 'verbose_name': 'РЎС‚Р°С‚СѓСЃ', 'verbose_name_plural': 'РЎС‚Р°С‚СѓСЃС‹'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'РўРµРі', 'verbose_name_plural': 'РўРµРіРё'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-created_at'], 'verbose_name': 'РўРёРєРµС‚', 'verbose_name_plural': 'РўРёРєРµС‚С‹'},
        ),
        migrations.AlterModelOptions(
            name='tickethistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'Р\x98СЃС‚РѕСЂРёСЏ', 'verbose_name_plural': 'Р\x98СЃС‚РѕСЂРёСЏ'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'РџСЂРѕС„РёР»СЊ РїРѕР»СЊР·РѕРІР°С‚РµР»СЏ', 'verbose_name_plural': 'РџСЂРѕС„РёР»Рё РїРѕР»СЊР·РѕРІР°С‚РµР»РµР№'},
        ),
        migrations.AlterModelOptions(
            name='workstation',
            options={'ordering': ['room', 'number'], 'verbose_name': 'Р\xa0Р°Р±РѕС‡РµРµ РјРµСЃС‚Рѕ', 'verbose_name_plural': 'Р\xa0Р°Р±РѕС‡РёРµ РјРµСЃС‚Р°'},
        ),
        migrations.AlterField(
            model_name='attachment',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.comment', verbose_name='РљРѕРјРјРµРЅС‚Р°СЂРёР№'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='РћРїРёСЃР°РЅРёРµ'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='tickets/attachments/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'pdf', 'doc', 'docx', 'xls', 'xlsx', 'txt', 'zip'])], verbose_name='Р¤Р°Р№Р»'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.ticket', verbose_name='РўРёРєРµС‚'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Р—Р°РіСЂСѓР¶РµРЅРѕ'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Р—Р°РіСЂСѓР¶РµРЅРѕ'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='РђРІС‚РѕСЂ'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(verbose_name='РЎРѕРґРµСЂР¶Р°РЅРёРµ'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='РЎРѕР·РґР°РЅРѕ'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_internal',
            field=models.BooleanField(default=False, verbose_name='Р’РЅСѓС‚СЂРµРЅРЅРёР№ РєРѕРјРјРµРЅС‚Р°СЂРёР№'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tickets.ticket', verbose_name='РўРёРєРµС‚'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='РћР±РЅРѕРІР»РµРЅРѕ'),
        ),
        migrations.AlterField(
            model_name='priority',
            name='color',
            field=models.CharField(default='#000000', help_text='HEX С†РІРµС‚', max_length=7),
        ),
        migrations.AlterField(
            model_name='priority',
            name='name',
            field=models.CharField(choices=[('low', 'РќРёР·РєРёР№'), ('medium', 'РЎСЂРµРґРЅРёР№'), ('high', 'Р’С‹СЃРѕРєРёР№'), ('critical', 'РљСЂРёС‚РёС‡РµСЃРєРёР№')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='color',
            field=models.CharField(default='#808080', help_text='HEX С†РІРµС‚', max_length=7),
        ),
        migrations.AlterField(
            model_name='status',
            name='is_final',
            field=models.BooleanField(default=False, help_text='Р¤РёРЅР°Р»СЊРЅС‹Р№ СЃС‚Р°С‚СѓСЃ'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(choices=[('open', 'РћС‚РєСЂС‹С‚'), ('in_progress', 'Р’ СЂР°Р±РѕС‚Рµ'), ('waiting', 'РћР¶РёРґР°РЅРёРµ'), ('resolved', 'Р\xa0РµС€РµРЅ'), ('closed', 'Р—Р°РєСЂС‹С‚'), ('reopened', 'РџРµСЂРµРѕС‚РєСЂС‹С‚')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='РќР°Р·РЅР°С‡РµРЅРѕ'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Р—Р°РєСЂС‹С‚Рѕ'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='РЎРѕР·РґР°РЅРѕ'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tickets', to=settings.AUTH_USER_MODEL, verbose_name='РЎРѕР·РґР°С‚РµР»СЊ'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(verbose_name='РћРїРёСЃР°РЅРёРµ'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='РЎСЂРѕРє РІС‹РїРѕР»РЅРµРЅРёСЏ'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='estimated_hours',
            field=models.FloatField(blank=True, null=True, verbose_name='Р\xa0Р°СЃС‡РµС‚РЅС‹Рµ С‡Р°СЃС‹'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.ForeignKey(default='medium', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.priority', verbose_name='РџСЂРёРѕСЂРёС‚РµС‚'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Р\xa0РµС€РµРЅРѕ'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='room',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='РљР°Р±РёРЅРµС‚/РћС„РёСЃ'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.ForeignKey(default='open', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.status', verbose_name='РЎС‚Р°С‚СѓСЃ'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tickets.tag', verbose_name='РўРµРіРё'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Р—Р°РіРѕР»РѕРІРѕРє'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='РћР±РЅРѕРІР»РµРЅРѕ'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user_urgency',
            field=models.CharField(choices=[('low', 'РќРёР·РєР°СЏ'), ('normal', 'РћР±С‹С‡РЅР°СЏ'), ('urgent', 'РЎСЂРѕС‡РЅРѕ'), ('critical', 'РљСЂРёС‚РёС‡РЅРѕ')], default='normal', max_length=20, verbose_name='Р—Р°РїСЂРѕС€РµРЅРЅР°СЏ СЃСЂРѕС‡РЅРѕСЃС‚СЊ'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='workstation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.workstation', verbose_name='Р\xa0Р°Р±РѕС‡РµРµ РјРµСЃС‚Рѕ/РљРѕРјРїСЊСЋС‚РµСЂ'),
        ),
        migrations.AlterField(
            model_name='tickethistory',
            name='action',
            field=models.CharField(choices=[('created', 'РЎРѕР·РґР°РЅ'), ('updated', 'РћР±РЅРѕРІР»РµРЅ'), ('assigned', 'РќР°Р·РЅР°С‡РµРЅ'), ('status_changed', 'РЎС‚Р°С‚СѓСЃ РёР·РјРµРЅРµРЅ'), ('priority_changed', 'РџСЂРёРѕСЂРёС‚РµС‚ РёР·РјРµРЅРµРЅ')], max_length=20, verbose_name='Р”РµР№СЃС‚РІРёРµ'),
        ),
        migrations.AlterField(
            model_name='tickethistory',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Р”РµР№СЃС‚РІСѓСЋС‰РµРµ Р»РёС†Рѕ'),
        ),
        migrations.AlterField(
            model_name='tickethistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='РЎРѕР·РґР°РЅРѕ'),
        ),
        migrations.AlterField(
            model_name='tickethistory',
            name='new_value',
            field=models.TextField(blank=True, verbose_name='РќРѕРІРѕРµ Р·РЅР°С‡РµРЅРёРµ'),
        ),
        migrations.AlterField(
            model_name='tickethistory',
            name='old_value',
            field=models.TextField(blank=True, verbose_name='РЎС‚Р°СЂРѕРµ Р·РЅР°С‡РµРЅРёРµ'),
        ),
        migrations.AlterField(
            model_name='tickethistory',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tickets.ticket', verbose_name='РўРёРєРµС‚'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Р”Р°С‚Р° РѕРґРѕР±СЂРµРЅРёСЏ'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_users', to=settings.AUTH_USER_MODEL, verbose_name='РћРґРѕР±СЂРµРЅ РїРѕР»СЊР·РѕРІР°С‚РµР»РµРј'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100, verbose_name='РћС‚РґРµР»'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='РћРґРѕР±СЂРµРЅ Р°РґРјРёРЅРёСЃС‚СЂР°С‚РѕСЂРѕРј'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='notify_browser',
            field=models.BooleanField(default=True, verbose_name='РЈРІРµРґРѕРјР»РµРЅРёСЏ РІ Р±СЂР°СѓР·РµСЂРµ'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='notify_email',
            field=models.BooleanField(default=True, verbose_name='Email СѓРІРµРґРѕРјР»РµРЅРёСЏ'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='notify_email_address',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email РґР»СЏ СѓРІРµРґРѕРјР»РµРЅРёР№'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='notify_vk',
            field=models.BooleanField(default=False, verbose_name='VK СѓРІРµРґРѕРјР»РµРЅРёСЏ'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='office_room',
            field=models.CharField(blank=True, max_length=50, verbose_name='РљР°Р±РёРЅРµС‚'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='РўРµР»РµС„РѕРЅ'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='РџРѕР»СЊР·РѕРІР°С‚РµР»СЊ'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='workstation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='tickets.workstation', verbose_name='Р\xa0Р°Р±РѕС‡РµРµ РјРµСЃС‚Рѕ/РљРѕРјРїСЊСЋС‚РµСЂ'),
        ),
        migrations.AlterField(
            model_name='workstation',
            name='location',
            field=models.CharField(blank=True, help_text='РћРїС†РёРѕРЅР°Р»СЊРЅРѕ: СѓС‚РѕС‡РЅС‘РЅРЅРѕРµ РјРµСЃС‚Рѕ СЂР°СЃРїРѕР»РѕР¶РµРЅРёСЏ', max_length=255, verbose_name='РџРѕРґСЂРѕР±РЅРѕРµ РјРµСЃС‚РѕРїРѕР»РѕР¶РµРЅРёРµ'),
        ),
        migrations.AlterField(
            model_name='workstation',
            name='number',
            field=models.CharField(help_text='РќР°РїСЂРёРјРµСЂ: "РџРљ-1", "Р›РµРІС‹Р№ СЃС‚РѕР»", "РњРѕРЅРёС‚РѕСЂ 3" Рё С‚.Рґ.', max_length=50, verbose_name='РќРѕРјРµСЂ/РћРїРёСЃР°РЅРёРµ'),
        ),
        migrations.AlterField(
            model_name='workstation',
            name='room',
            field=models.CharField(max_length=100, verbose_name='РљР°Р±РёРЅРµС‚/РћС„РёСЃ'),
        ),
    ]
