# Generated by Django 5.0 on 2026-04-05 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_alter_attachment_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='priority',
            options={'ordering': ['-name'], 'verbose_name': 'Приоритет', 'verbose_name_plural': 'Приоритеты'},
        ),
        migrations.AlterModelOptions(
            name='status',
            options={'ordering': ['name'], 'verbose_name': 'Статус', 'verbose_name_plural': 'Статусы'},
        ),
        migrations.AlterField(
            model_name='priority',
            name='color',
            field=models.CharField(default='#000000', help_text='HEX цвет', max_length=7),
        ),
        migrations.AlterField(
            model_name='priority',
            name='name',
            field=models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('critical', 'Критический')], max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='status',
            name='color',
            field=models.CharField(default='#808080', help_text='HEX цвет', max_length=7),
        ),
        migrations.AlterField(
            model_name='status',
            name='is_final',
            field=models.BooleanField(default=False, help_text='Финальный статус'),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(choices=[('open', 'Открыт'), ('in_progress', 'В работе'), ('waiting', 'Ожидание'), ('resolved', 'Решен'), ('closed', 'Закрыт'), ('reopened', 'Переоткрыт')], max_length=20, unique=True),
        ),
    ]
