# Generated by Django 5.0 on 2026-04-06 14:40

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_normalize_priority_status_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attachment',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Вложение', 'verbose_name_plural': 'Вложения'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-created_at'], 'verbose_name': 'Тикет', 'verbose_name_plural': 'Тикеты'},
        ),
        migrations.AlterModelOptions(
            name='tickethistory',
            options={'ordering': ['-created_at'], 'verbose_name': 'История', 'verbose_name_plural': 'История'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователей'},
        ),
        migrations.AlterModelOptions(
            name='workstation',
            options={'ordering': ['room', 'number'], 'verbose_name': 'Рабочее место', 'verbose_name_plural': 'Рабочие места'},
        ),
        migrations.AlterField(
            model_name='attachment',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.comment', verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to='tickets/attachments/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'pdf', 'doc', 'docx', 'xls', 'xlsx', 'txt', 'zip'])], verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.ticket', verbose_name='Тикет'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Загружено'),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Загружено'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(blank=True, verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_internal',
            field=models.BooleanField(default=False, verbose_name='Внутренний комментарий'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tickets.ticket', verbose_name='Тикет'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Назначено'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Закрыто'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Желаемый срок решения'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='estimated_hours',
            field=models.FloatField(blank=True, null=True, verbose_name='Расчетные часы'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.ForeignKey(default='medium', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.priority', verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Решено'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='room',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Кабинет/Офис'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.ForeignKey(default='open', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.status', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='tags',
            field=models.ManyToManyField(blank=True, to='tickets.tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user_urgency',
            field=models.CharField(choices=[('low', 'РќРёР·РєР°СЏ'), ('normal', 'РћР±С‹С‡РЅР°СЏ'), ('urgent', 'РЎСЂРѕС‡РЅРѕ'), ('critical', 'РљСЂРёС‚РёС‡РЅРѕ')], default='normal', max_length=20, verbose_name='Запрошенная срочность'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='workstation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.workstation', verbose_name='Рабочее место/Компьютер'),
        ),
        migrations.AlterField(
            model_name='tickethistory',
            name='action',
            field=models.CharField(choices=[('created', 'Создан'), ('updated', 'Обновлен'), ('assigned', 'Назначен'), ('status_changed', 'Статус изменен'), ('priority_changed', 'Приоритет изменен')], max_length=20, verbose_name='Действие'),
        ),
        migrations.AlterField(
            model_name='tickethistory',
            name='actor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Действующее лицо'),
        ),
        migrations.AlterField(
            model_name='tickethistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='tickethistory',
            name='new_value',
            field=models.TextField(blank=True, verbose_name='Новое значение'),
        ),
        migrations.AlterField(
            model_name='tickethistory',
            name='old_value',
            field=models.TextField(blank=True, verbose_name='Старое значение'),
        ),
        migrations.AlterField(
            model_name='tickethistory',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tickets.ticket', verbose_name='Тикет'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата одобрения'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_users', to=settings.AUTH_USER_MODEL, verbose_name='Одобрен пользователем'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100, verbose_name='Отдел'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Одобрен администратором'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='notify_browser',
            field=models.BooleanField(default=True, verbose_name='Уведомления в браузере'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='notify_email',
            field=models.BooleanField(default=True, verbose_name='Email уведомления'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='notify_email_address',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email для уведомлений'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='notify_vk',
            field=models.BooleanField(default=False, verbose_name='VK уведомления'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='office_room',
            field=models.CharField(blank=True, max_length=50, verbose_name='Кабинет'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='workstation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='tickets.workstation', verbose_name='Рабочее место/Компьютер'),
        ),
        migrations.AlterField(
            model_name='workstation',
            name='location',
            field=models.CharField(blank=True, help_text='Опционально: уточненное место расположения.', max_length=255, verbose_name='Подробное местоположение'),
        ),
        migrations.AlterField(
            model_name='workstation',
            name='number',
            field=models.CharField(help_text='Например: "ПК-1", "Левый стол", "Монитор 3".', max_length=50, verbose_name='Номер/Описание'),
        ),
        migrations.AlterField(
            model_name='workstation',
            name='room',
            field=models.CharField(max_length=100, verbose_name='Кабинет/Офис'),
        ),
    ]
